import { createSlice } from "@reduxjs/toolkit";
import { USE_TEST_DATA } from "../../Utils/settings";
import {
  tileOrder,
  diceIdOrder,
  portOrder,
  tileData,
  devCards,
  nodeData,
  roadData
} from "../../Utils/testData";

const initialState =
  USE_TEST_DATA ?
    {
      gameId: -1,
      tileOrder,
      diceIdOrder,
      portOrder,
      tileData,
      nodeData,
      roadData,
      devCards,
      positionedTiles: [],
      positionedDiceIds: [],
      positionedNodes: {},
      positionedRoads: {},
      constructRoadEnabled: false,
      constructBuildingEnabled: false,
      robberLocation: null,
    }
    :
    {
      // GENERATED BY SERVER
      gameId: -1,
      // GENERATED ONCE THEN STATIC
      tileOrder: [],
      diceIdOrder: [],
      portOrder: [],
      // GENERATED EACH TIME GAME IS OPENED
      positionedTiles: [],
      positionedDiceIds: [],
      positionedNodes: {},
      positionedRoads: {},
      tileData: {},
      // GENERATED ONCE THEN MODIFIED
      devCards: [],
      nodeData: {},
      roadData: {},
      // FLAGS
      constructRoadEnabled: false,
      constructBuildingEnabled: false,
      // MISC VALUES
      robberLocation: null,
    };

const gameSlice = createSlice(
  {
    name: 'game',
    initialState: initialState,
    reducers:
    {
      initializeGameData(state, action) {
        return { ...state, ...action.payload };
      },
      clearGameData(state) {
        return initialState;
      },
      setTileData(state, action) {
        state.tileData = action.payload;
      },
      setNodeData(state, action) {
        state.nodeData = action.payload;
      },
      setRoadData(state, action) {
        state.roadData = action.payload;
      },
      setRoadConstructionIsEnabled(state, action) {
        state.constructRoadEnabled = action.payload.isEnabled;
      },
      setBuildingConstructionIsEnabled(state, action) {
        state.constructBuildingEnabled = action.payload.isEnabled;
      },
      setPositionData(state, action) {
        return { ...state, ...action.payload };
      },
    }
  }
);

export const gameActions = gameSlice.actions;
export default gameSlice;